name: Deploy Affected
on:
  push:
    branches:
      - 'master'
      - 'e4p/sprint/**' # eventually this should just be master

jobs:
  environment-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Print steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Print runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Print strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Print matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: Install Dependencies
  #       run: |
  #         npm ci
  unit-tests:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: |
          npm ci
      - name: Unit Tests
        shell: bash
        run: |
          npm run affected:test -- --base=origin/master~1 --head=origin/master --parallel --maxParallel=2

  end-to-end:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: |
          npm ci
      - name: End-to-End
        shell: bash
        run: |
          npm run affected:e2e -- --base=origin/master~1 --head=origin/master --parallel --maxParallel=2

  build:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        shell: bash
        run: |
          npm run affected:build -- --base=6903fd9f76905fcd52163c5fdca414841b433fc7 --head=838c1276447b05b2e7e8a9e06fdb38e2594d4903 --prod --parallel --maxParallel=2
      - name: List Affected Apps
        shell: bash
        run: |
          npx nx print-affected --target=build --select=tasks.target.project --base=6903fd9f76905fcd52163c5fdca414841b433fc7 --head=838c1276447b05b2e7e8a9e06fdb38e2594d4903
      - name: 'List Files'
        shell: bash
        run: |
          ls -al dist/apps

  deploy:
    runs-on: ubuntu-latest
    needs: ['unit-tests', 'build', 'end-to-end']
    steps:
      - name: 'Test'
        shell: bash
        run: |
          ls -al
